// (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(dead_code)]

// When building with Cargo, use bindings generated by build.rs via the cc + bindgen crates.
// The cargo_bindgen feature is a default feature in Cargo.toml, but is not set by other build systems.
#[cfg(feature = "cargo_bindgen")]
include!(concat!(env!("OUT_DIR"), "/renderer_c.rs"));

#[cfg(not(feature = "cargo_bindgen"))]
pub use haptic_renderer_rs::*;
