// (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

use haptic_dsp::RmsEnvelopeFollower;
use serde::Deserialize;
use serde::Serialize;
use typeshare::typeshare;

use crate::breakpoint_reduction::Breakpoint;
use crate::emphasis_detection::Emphasis;

/// The settings used by AmplitudeAnalyzer
#[derive(Copy, Clone, Debug, Serialize, Deserialize)]
#[typeshare]
pub struct AmplitudeAnalysisSettings {
    /// The amount of time between events generated by the amplitude analyzer
    pub time_between_updates: f32,
    /// The envelope follower's attack time
    pub envelope_attack_time: f32,
    /// The envelope follower's hold time
    pub envelope_hold_time: f32,
    /// The envelope follower's release time
    pub envelope_release_time: f32,
    /// The size in time of the RMS window used by the envelope follower
    pub rms_windowing_time: f32,
}

impl Default for AmplitudeAnalysisSettings {
    fn default() -> Self {
        Self {
            time_between_updates: 1.0e-3,    // 1ms
            envelope_attack_time: 1.0e-4,    // 0.1ms
            envelope_hold_time: 1.5e-3,      // 1.5ms
            envelope_release_time: 100.0e-3, // 100ms
            rms_windowing_time: 1.0e-4,      // 0.1ms
        }
    }
}

/// The event type generated by AmplitudeAnalyzer
#[derive(Copy, Clone, Debug, Default, PartialEq)]
pub struct AmplitudeEvent {
    /// The event's time
    pub time: f32,
    /// The event's amplitude
    pub amplitude: f32,
    /// Optional Emphasis attached to the amplitude event
    pub emphasis: Option<Emphasis>,
}

impl Breakpoint for AmplitudeEvent {
    fn time(&self) -> f32 {
        self.time
    }

    fn value(&self) -> f32 {
        self.amplitude
    }
}

/// The amplitude analyzer used in offline analysis
///
/// The amplitude analyzer uses an RMS envelope follower to generate a smoothed curve for the
/// amplitude signal, generating events at a fixed rate along the curve.
///
/// The analyzer is implemented as an iterator to allow for transformations on its output
/// (i.e. to create different event types) without needing temporary containers
///
/// See also: [`audio_to_haptics`, `AmplitudeAnalysisSettings`, `FrequencyAnalyzer`]
pub struct AmplitudeAnalyzer<'input> {
    input: &'input [f32],
    amplitude_follower: RmsEnvelopeFollower,
    index: usize,
    time_between_samples: f32,
    time_between_updates: f32,
    next_update_time: Option<f32>,
}

impl<'input> AmplitudeAnalyzer<'input> {
    /// Initializes a new AmplitudeAnalyzer for the provided input data
    pub fn new(
        input: &'input [f32],
        sample_rate: f32,
        settings: AmplitudeAnalysisSettings,
    ) -> Self {
        Self {
            input,
            amplitude_follower: RmsEnvelopeFollower::new(
                settings.rms_windowing_time,
                settings.envelope_attack_time,
                settings.envelope_hold_time,
                settings.envelope_release_time,
                sample_rate,
            ),
            index: 0,
            time_between_samples: 1.0 / sample_rate,
            time_between_updates: settings.time_between_updates,
            next_update_time: Some(settings.time_between_updates),
        }
    }
}

impl<'input> Iterator for AmplitudeAnalyzer<'input> {
    type Item = AmplitudeEvent;

    fn next(&mut self) -> Option<Self::Item> {
        if let Some(next_update_time) = self.next_update_time {
            let mut rms = 0.0;
            let mut time = self.index as f32 * self.time_between_samples;

            // Keep processing input samples until we reach the next update time
            while time < next_update_time {
                // Get the next sample of input. If the time of the next update extends past
                // the end of the input, then process silence
                let input = *self.input.get(self.index).unwrap_or(&0.0);
                rms = self.amplitude_follower.process(input);

                self.index += 1;
                time = self.index as f32 * self.time_between_samples;
            }

            // Schedule the next update
            self.next_update_time = if self.index < self.input.len() {
                Some(next_update_time + self.time_between_updates)
            } else {
                None
            };

            // Return the last rms output as the 'amplitude' value
            Some(AmplitudeEvent {
                time,
                amplitude: rms.min(1.0), // Avoid amplitudes above 1.0
                emphasis: None,
            })
        } else {
            None
        }
    }
}

#[cfg(test)]
mod tests {
    use haptic_dsp::test_utils::is_near;

    use super::*;

    fn run_amplitude_analyzer_test(
        input: &[f32],
        sample_rate: f32,
        settings: AmplitudeAnalysisSettings,
        expected_time_and_amplitudes: &[(f32, f32)],
    ) {
        let result: Vec<AmplitudeEvent> =
            AmplitudeAnalyzer::new(input, sample_rate, settings).collect();
        let expected_events: Vec<AmplitudeEvent> = expected_time_and_amplitudes
            .iter()
            .cloned()
            .map(|(time, amplitude)| AmplitudeEvent {
                time,
                amplitude,
                emphasis: None,
            })
            .collect();

        for (index, (expected, actual)) in expected_events.iter().zip(result.iter()).enumerate() {
            let allowed_error = 1.0e-4;

            if !is_near(expected.time, actual.time, allowed_error) {
                panic!(
                    "Mismatch in event time at position {}, expected: {:?}, actual: {:?}\
                 \n  expected events: {:#?}\
                 \n  actual events: {:#?}\n",
                    index, expected.time, actual.time, expected_events, result
                );
            }
            if !is_near(expected.amplitude, actual.amplitude, allowed_error) {
                panic!(
                    "Mismatch in event frequency at position {}, expected: {:?}, actual: {:?}\
                 \n  expected events: {:#?}\
                 \n  actual events: {:#?}\n",
                    index, expected.amplitude, actual.amplitude, expected_events, result
                );
            }
        }
    }

    #[test]
    fn basic_rms_output() {
        let sample_rate = 1.0;

        let settings = AmplitudeAnalysisSettings {
            time_between_updates: 1.0,
            envelope_attack_time: 0.0,
            envelope_hold_time: 0.0,
            envelope_release_time: 0.0,
            rms_windowing_time: 2.0,
        };

        // 1 for 2 seconds, 0 for 2 seconds
        let input = [1.0, 1.0, 0.0, 0.0];
        // 2 second windowing time produces a ramped output, up to 1 and back down to 0
        use std::f32::consts::FRAC_1_SQRT_2;
        let expected = [
            (1.0, FRAC_1_SQRT_2),
            (2.0, 1.0),
            (3.0, FRAC_1_SQRT_2),
            (4.0, 0.0),
        ];

        run_amplitude_analyzer_test(&input, sample_rate, settings, &expected);
    }

    #[test]
    fn rms_gets_clamped() {
        let sample_rate = 1.0;

        let settings = AmplitudeAnalysisSettings {
            time_between_updates: 1.0,
            envelope_attack_time: 0.0,
            envelope_hold_time: 0.0,
            envelope_release_time: 0.0,
            rms_windowing_time: 1.0,
        };

        // A ramp up to values above above 1
        let input = [0.0, 1.0, 2.0, 3.0];

        // We want amplitude output to be clamped to 1
        let expected = [(1.0, 0.0), (2.0, 1.0), (3.0, 1.0), (4.0, 1.0)];

        run_amplitude_analyzer_test(&input, sample_rate, settings, &expected);
    }
}
