// Copyright (c) Meta Platforms, Inc. and affiliates.
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.

use serde::Deserialize;
use serde::Serialize;
use typeshare::typeshare;

use crate::breakpoint_reduction::Breakpoint;
use crate::spectrum_analysis::SpectralFeatures;

/// The settings used by the FrequencyAnalyzer
///
/// See [crate::OfflineAnalysisSettings].
#[derive(Copy, Clone, Debug, Serialize, Deserialize)]
#[typeshare]
pub struct FrequencyAnalysisSettings {
    /// The frequency in Hz that represents the minimum of the analyzed range
    pub frequency_min: f32,
    /// The frequency in Hz that represents the maximum of the analyzed range
    pub frequency_max: f32,
    /// The value from 0 -> 1 that represents the minimum of the output range
    pub output_min: f32,
    /// The value from 0 -> 1 that represents the maximum of the output range
    pub output_max: f32,
}

impl Default for FrequencyAnalysisSettings {
    fn default() -> Self {
        Self {
            frequency_min: 30.0,
            frequency_max: 600.0,
            output_min: 0.0,
            output_max: 1.0,
        }
    }
}

// The event type generated by FrequencyAnalyzer
#[derive(Copy, Clone, Debug, Default, PartialEq)]
pub(crate) struct FrequencyEvent {
    /// The frequency event's time in seconds
    pub time: f32,
    /// The event's frequency
    pub frequency: f32,
}

impl Breakpoint for FrequencyEvent {
    fn time(&self) -> f32 {
        self.time
    }

    fn value(&self) -> f32 {
        self.frequency
    }
}

pub(crate) fn analyze_frequency(
    spectral_features: &[SpectralFeatures],
    sample_rate: f32,
    settings: FrequencyAnalysisSettings,
) -> Vec<FrequencyEvent> {
    let nyquist = sample_rate / 2.0;
    let scale_in_min = settings.frequency_min / nyquist;
    let scale_in_max = settings.frequency_max / nyquist;
    let scale_in_range = scale_in_max - scale_in_min;
    let scale_out_min = settings.output_min;
    let scale_out_range = settings.output_max - settings.output_min;

    spectral_features
        .iter()
        // Event times are placed in the center of the analysis window.
        // When using an overlap factor greater than 2, the first windows will be centered before
        // time 0, due to the spectral analyzer returning analyzed windows after a single hop.
        // We don't want to output events with a negative time, so they can be filtered out here.
        .filter(|frame| frame.time >= 0.0)
        .map(|frame| {
            // Scale the frame's centroid value so that it corresponds to the scaling settings
            let in_scaled = (frame.centroid - scale_in_min) / (scale_in_range);
            let out_scaled = in_scaled * (scale_out_range) + scale_out_min;
            let frequency = out_scaled.clamp(0.0, 1.0);
            FrequencyEvent {
                time: frame.time,
                frequency,
            }
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use haptic_dsp::test_utils::is_near;

    use super::*;

    fn run_frequency_analyzer_test(
        spectral_features: &[SpectralFeatures],
        sample_rate: f32,
        settings: FrequencyAnalysisSettings,
        expected_events: &[FrequencyEvent],
    ) {
        let result = analyze_frequency(spectral_features, sample_rate, settings);

        for (index, (expected, actual)) in expected_events.iter().zip(result.iter()).enumerate() {
            let allowed_error = 1.0e-4;

            if !is_near(expected.time, actual.time, allowed_error) {
                panic!(
                    "Mismatch in event time at position {}, expected: {:?}, actual: {:?}\
                 \n  expected events: {:#?}\
                 \n  actual events: {:#?}\n",
                    index, expected.time, actual.time, expected_events, result
                );
            }
            if !is_near(expected.frequency, actual.frequency, allowed_error) {
                panic!(
                    "Mismatch in event frequency at position {}, expected: {:?}, actual: {:?}\
                 \n  expected events: {:#?}\
                 \n  actual events: {:#?}\n",
                    index, expected.frequency, actual.frequency, expected_events, result
                );
            }
        }
    }

    fn spectral_features(time: f32, centroid: f32) -> SpectralFeatures {
        SpectralFeatures {
            time,
            centroid,
            flux: 0.0,
        }
    }

    fn frequency_event(time: f32, frequency: f32) -> FrequencyEvent {
        FrequencyEvent { time, frequency }
    }

    #[test]
    fn filter_negative_frame_times() {
        let sample_rate = 1024.0;
        let nyquist = sample_rate / 2.0;

        let settings = FrequencyAnalysisSettings {
            frequency_min: 0.0,
            frequency_max: nyquist,
            output_min: 0.0,
            output_max: 1.0,
        };

        let spectral_features = [
            spectral_features(-0.5, 0.0125),
            spectral_features(0.5, 0.125),
            spectral_features(1.5, 0.25),
            spectral_features(2.5, 0.375),
        ];

        let expected_output = [
            frequency_event(0.5, 0.125),
            frequency_event(1.5, 0.25),
            frequency_event(2.5, 0.375),
        ];

        run_frequency_analyzer_test(&spectral_features, sample_rate, settings, &expected_output);
    }

    #[test]
    fn output_reduced_by_half() {
        let sample_rate = 1024.0;
        let nyquist = sample_rate / 2.0;

        let settings = FrequencyAnalysisSettings {
            frequency_min: 0.0,
            frequency_max: nyquist,
            output_min: 0.0,
            output_max: 0.5,
        };

        let spectral_features = [
            spectral_features(0.5, 0.125),
            spectral_features(1.5, 0.25),
            spectral_features(2.5, 0.375),
        ];

        // Compared to when there's no scaling, the frequency values are reduced by half.
        let expected_output = [
            frequency_event(0.5, 0.0625),
            frequency_event(1.5, 0.125),
            frequency_event(2.5, 0.1875),
        ];

        run_frequency_analyzer_test(&spectral_features, sample_rate, settings, &expected_output);
    }

    #[test]
    fn input_reduced_by_33_percent() {
        let sample_rate = 1024.0;
        let nyquist = sample_rate / 2.0;

        let settings = FrequencyAnalysisSettings {
            frequency_min: 0.0,
            frequency_max: nyquist * 2.0 / 3.0,
            output_min: 0.0,
            output_max: 1.0,
        };

        let spectral_features = [
            spectral_features(0.5, 0.125),
            spectral_features(1.5, 0.25),
            spectral_features(2.5, 0.375),
        ];

        // The frequency values are effectively doubled, and then clamped at 1.0
        let expected_output = [
            frequency_event(0.5, 0.1875),
            frequency_event(1.5, 0.375),
            frequency_event(2.5, 0.5625),
        ];

        run_frequency_analyzer_test(&spectral_features, sample_rate, settings, &expected_output);
    }

    #[test]
    fn input_reduced_by_33_percent_and_output_scaled_up() {
        let sample_rate = 1024.0;
        let nyquist = sample_rate / 2.0;

        let settings = FrequencyAnalysisSettings {
            frequency_min: 0.0,
            frequency_max: nyquist * 2.0 / 3.0,
            output_min: 0.5,
            output_max: 1.0,
        };

        let spectral_features = [
            spectral_features(0.5, 0.125),
            spectral_features(1.5, 0.25),
            spectral_features(2.5, 0.375),
        ];

        // The frequency values are effectively doubled, and then clamped at 1.0
        let expected_output = [
            frequency_event(0.5, 0.59375),
            frequency_event(1.5, 0.6875),
            frequency_event(2.5, 0.78125),
        ];

        run_frequency_analyzer_test(&spectral_features, sample_rate, settings, &expected_output);
    }
}
