// Copyright (c) Meta Platforms, Inc. and affiliates.
//
// This source code is licensed under the MIT license found in the
// LICENSE file in the root directory of this source tree.

//! # Spectrum analysis
//!
//! This module provides a spectral feature extractor that provides the features needed during
//! haptic analysis.

use haptic_dsp::Complex;
use haptic_dsp::SpectralAnalyzer;
use haptic_dsp::SpectralAnalyzerSettings;
use haptic_dsp::Window;
use haptic_dsp::spectral_centroid;
use haptic_dsp::spectral_flux;
use serde::Deserialize;
use serde::Serialize;
use typeshare::typeshare;

/// The settings used by the SpectrumAnalyzer
///
/// See [crate::OfflineAnalysisSettings]
#[derive(Copy, Clone, Debug, Serialize, Deserialize)]
#[typeshare]
pub struct SpectrumAnalysisSettings {
    /// The FFT window size to be used during spectrum analysis
    pub fft_size: u32,
    /// The FFT window overlap factor
    /// The minimum value is 1, which implies no overlap
    pub overlap_factor: u32,
    /// The cutoff of the brickwall lowpass filter that's applied before centroid analysis
    pub centroid_lowpass_hz: f32,
}

impl Default for SpectrumAnalysisSettings {
    fn default() -> Self {
        Self {
            fft_size: 1024,
            overlap_factor: 8,
            centroid_lowpass_hz: 1000.0,
        }
    }
}

/// The output type generated by SpectrumAnalyzer
#[derive(Copy, Clone, Debug, Default, PartialEq)]
pub struct SpectralFeatures {
    // The time of the center of an analyzed frame
    pub time: f32,
    pub centroid: f32,
    pub flux: f32,
}

/// A spectrum analyzer that extracts features needed by haptic analysis
pub(crate) struct SpectrumAnalyzer<'input> {
    // The FFT analyzer that will be used for analysis
    fft_analyzer: SpectralAnalyzer,
    // The input signal
    input: &'input [f32],
    // The current input index
    index: usize,
    // We want to keep processing until we have a frame that's centered on the end of the input
    // signal, so here we cache the input length plus half_fft_size.
    last_index: usize,
    // The amount of time that a sample represents, used in event time calculation
    sample_duration: f32,
    // We want to return the time of the center of the analysis window as the event time,
    // so this offset is subtracted from the time at the end of the window when generating events.
    half_window_duration: f32,
    // Useful when iterating over the bins up to nyquist
    half_fft_size: usize,

    // First bin to filter when analyzing spectral centroid
    filter_bin_start: usize,
    // Number of bins to filter when analyzing spectral centroid
    filter_bin_count: usize,
    // Minimum spectral energy to be
    minimum_spectral_energy: f32,

    // The current frame's bin magnitudes
    magnitudes: Vec<f32>,
    // The previous frame's bin magnitudes
    previous_magnitudes: Vec<f32>,
}

impl<'input> SpectrumAnalyzer<'input> {
    pub fn new(input: &'input [f32], sample_rate: f32, settings: SpectrumAnalysisSettings) -> Self {
        let sample_duration = 1.0 / sample_rate;
        let half_window_duration = sample_duration * settings.fft_size as f32 / 2.0;
        let half_fft_size = settings.fft_size as usize / 2;

        // Find the first bin above the maximum input frequency to start applying filtering.
        let nyquist = sample_rate / 2.0;
        let centroid_lowpass_hz_normalized = settings.centroid_lowpass_hz / nyquist;
        let filter_bin_start =
            (half_fft_size as f32 * centroid_lowpass_hz_normalized).ceil() as usize;
        // The spectral_centroid function ignores bins above nyquist,
        // so filtering is only needed up to the nyquist bin.
        let filter_bin_count = half_fft_size - filter_bin_start;

        // Set the minimum spectral energy for centroid calculations as a value derived from
        // a mean of a magnitude of '1' per unfiltered bin (above DC).
        // The scaling factor was found through manual testing as being a sweet spot that avoids
        // the centroid value shooting off towards infinity for quiet signals.
        let min_spectral_energy_scaling_factor = 0.3;
        let minimum_spectral_energy =
            ((filter_bin_start - 1) as f32) * min_spectral_energy_scaling_factor;

        Self {
            fft_analyzer: SpectralAnalyzer::new(SpectralAnalyzerSettings {
                fft_size: settings.fft_size as usize,
                overlap_factor: settings.overlap_factor as usize,
                window: Window::HanningZ,
            }),
            input,
            index: 0,
            last_index: input.len() + half_fft_size,
            sample_duration,
            half_window_duration,
            half_fft_size,
            filter_bin_start,
            filter_bin_count,
            minimum_spectral_energy,
            magnitudes: Vec::with_capacity(half_fft_size),
            previous_magnitudes: vec![0.0; half_fft_size],
        }
    }
}

impl<'input> Iterator for SpectrumAnalyzer<'input> {
    type Item = SpectralFeatures;

    fn next(&mut self) -> Option<Self::Item> {
        // Consume input samples until a new spectrum frame is produced
        while self.index < self.last_index {
            let input = self.input.get(self.index).unwrap_or(&0.0);
            self.index += 1;

            if let Some(fft_buffer) = self.fft_analyzer.process(*input) {
                // Set the time so that it's placed at the center of the frame
                let time = self.index as f32 * self.sample_duration - self.half_window_duration;

                let flux = {
                    // For spectral flux, we need the frame's magnitudes from 0 up to nyquist
                    self.magnitudes.clear();
                    self.magnitudes.extend(
                        fft_buffer[0..self.half_fft_size]
                            .iter()
                            .map(|bin| bin.norm()),
                    );
                    spectral_flux(&self.magnitudes, &self.previous_magnitudes)
                };

                // Note that centroid analysis modifies the input frame,
                // so this should be taken into account when adding more features in the future.
                let centroid = {
                    // Sum the non-filtered bin magnitudes
                    let spectral_energy: f32 =
                        self.magnitudes[..self.filter_bin_start].iter().sum();

                    if spectral_energy >= self.minimum_spectral_energy {
                        // Before taking the frame's centroid, apply a lowpass filter by zeroing
                        // bins that are above the maximum input frequency setting.
                        //
                        // With Rust 1.50, slice::fill could be used here:
                        // fft_buffer[self.filter_bin_range].fill(Complex::new(0.0, 0.0));
                        //
                        // Note that the Python implementation uses a time-domain filter,
                        // and using spectral filtering is a cheap solution that will do for now.
                        for bin in fft_buffer
                            .iter_mut()
                            .skip(self.filter_bin_start)
                            .take(self.filter_bin_count)
                        {
                            *bin = Complex::new(0.0, 0.0);
                        }

                        spectral_centroid(fft_buffer)
                    } else {
                        // If the energy in the signal is below the threshold, then just return 0.0
                        0.0
                    }
                };

                // Cache the current frame's magnitudes in previous_magnitudes
                std::mem::swap(&mut self.magnitudes, &mut self.previous_magnitudes);

                return Some(SpectralFeatures {
                    time,
                    centroid,
                    flux,
                });
            }
        }

        None
    }
}

#[cfg(test)]
mod tests {
    use haptic_dsp::test_utils::is_near;
    use haptic_dsp::test_utils::make_sine;

    use super::*;

    fn spectral_features(time: f32, centroid: f32, flux: f32) -> SpectralFeatures {
        SpectralFeatures {
            time,
            centroid,
            flux,
        }
    }

    fn run_spectrum_analyzer_test(
        input: &[f32],
        sample_rate: f32,
        settings: SpectrumAnalysisSettings,
        expected_output: &[SpectralFeatures],
    ) {
        let result: Vec<SpectralFeatures> =
            SpectrumAnalyzer::new(input, sample_rate, settings).collect();

        for (index, (expected, actual)) in expected_output.iter().zip(result.iter()).enumerate() {
            let allowed_error = 1.0e-3;

            if !is_near(expected.time, actual.time, allowed_error) {
                panic!(
                    "Mismatch in event time at position {}, expected: {:?}, actual: {:?}\
                 \n  expected events: {:#?}\
                 \n  actual events: {:#?}\n",
                    index, expected.time, actual.time, expected_output, result
                );
            }
            if !is_near(expected.centroid, actual.centroid, allowed_error) {
                panic!(
                    "Mismatch in event centroid at position {}, expected: {:?}, actual: {:?}\
                 \n  expected events: {:#?}\
                 \n  actual events: {:#?}\n",
                    index, expected.centroid, actual.centroid, expected_output, result
                );
            }
            if !is_near(expected.flux, actual.flux, allowed_error) {
                panic!(
                    "Mismatch in event flux at position {}, expected: {:?}, actual: {:?}\
                 \n  expected events: {:#?}\
                 \n  actual events: {:#?}\n",
                    index, expected.flux, actual.flux, expected_output, result
                );
            }
        }
    }

    fn low_mid_high_signal(sample_rate: f32) -> Vec<f32> {
        let nyquist = sample_rate / 2.0;
        let f = nyquist / 8.0;
        let one_second = sample_rate as usize;

        let mut result = Vec::new();
        // Start with a low frequency
        result.append(&mut make_sine(sample_rate, f, one_second));
        // Then, a mid frequency
        result.append(&mut make_sine(sample_rate, f * 2.0, one_second));
        // Then, a high frequency
        result.append(&mut make_sine(sample_rate, f * 3.0, one_second));
        result
    }

    fn centered_impulse_signal(size: usize) -> Vec<f32> {
        let mut result = vec![0.0; size];
        result[size / 2] = 1.0;
        result
    }

    #[test]
    fn no_centroid_filtering_1024() {
        let sample_rate = 1024.0;
        let nyquist = sample_rate / 2.0;

        let settings = SpectrumAnalysisSettings {
            fft_size: sample_rate as u32,
            overlap_factor: 1,
            centroid_lowpass_hz: nyquist,
        };

        let input = low_mid_high_signal(sample_rate);

        let expected = [
            spectral_features(0.5, 0.125, 512.256), // low
            spectral_features(1.5, 0.25, 0.021),    // mid
            spectral_features(2.5, 0.375, 0.046),   // high
        ];

        run_spectrum_analyzer_test(&input, sample_rate, settings, &expected);
    }

    #[test]
    fn no_centroid_filtering_2048() {
        let sample_rate = 2048.0;
        let nyquist = sample_rate / 2.0;

        let settings = SpectrumAnalysisSettings {
            fft_size: sample_rate as u32,
            overlap_factor: 1,
            centroid_lowpass_hz: nyquist,
        };

        let input = low_mid_high_signal(sample_rate);

        let expected = [
            spectral_features(0.5, 0.125, 1024.328), // low
            spectral_features(1.5, 0.25, 0.119),     // mid
            spectral_features(2.5, 0.375, 0.315),    // high
        ];

        run_spectrum_analyzer_test(&input, sample_rate, settings, &expected);
    }

    #[test]
    fn centroid_filtered_by_half_1024() {
        let sample_rate = 1024.0;
        let nyquist = sample_rate / 2.0;

        let settings = SpectrumAnalysisSettings {
            fft_size: sample_rate as u32,
            overlap_factor: 1,
            centroid_lowpass_hz: nyquist / 2.0,
        };

        let one_second = sample_rate as usize;
        let input = centered_impulse_signal(one_second);

        let expected = [
            // The resulting centroid is ~0.25, because:
            //   - The frequency range is [0, nyquist / 2]
            //   - Filtering reduces the frequency content above (nyquist / 2)
            //   - The resulting centroid is then 0.25 (center of the filtered signal below nyquist)
            // The resulting flux is 512, because:
            //   - The sum of magnitudes in the bins below nyquist in the initial frame is 512
            //   - The filtering for centroid doesn't affect the flux analysis
            spectral_features(0.5, 0.252, 512.0),
        ];

        run_spectrum_analyzer_test(&input, sample_rate, settings, &expected);
    }

    #[test]
    fn impulse_shows_flux_increase_later_in_signal_1024() {
        let sample_rate = 1024.0;
        let nyquist = sample_rate / 2.0;

        let settings = SpectrumAnalysisSettings {
            fft_size: sample_rate as u32,
            overlap_factor: 1,
            centroid_lowpass_hz: nyquist,
        };

        // A three second signal will place the impulse in the center of the second frame
        let three_seconds = 3 * sample_rate as usize;
        let input = centered_impulse_signal(three_seconds);

        let expected = [
            spectral_features(0.5, 0.0, 0.0),   // silence
            spectral_features(1.5, 0.5, 512.0), // impulse
            spectral_features(2.5, 0.0, 0.0),   // silence
        ];

        run_spectrum_analyzer_test(&input, sample_rate, settings, &expected);
    }
}
