default: test

clean:
  rm -rf build

build:
  mkdir -p build
  cd build && cmake ..
  cd build && cmake --build .

test:
  just build
  build/tests/test_continuous_oscillator
  build/tests/test_emphasis_oscillator
  build/tests/test_phasor
  build/tests/test_ramped_value